package main

import (
	"bufio"
	"crypto/subtle"
	"io"
	"strings"
)

// The gateway's half of authentication (slice-02 half two, D2/D3/D4).
//
// **THERE IS NO TOKEN FORMAT IN THIS FILE, DELIBERATELY** (GM, 2026-07-29: "we need to fix the cross
// language drift").
//
// The first version implemented `p42_<id>_<mac>` here as well as in Swift, and pinned the two together
// with a shared test vector. A gate is not a fix: two implementations of one format can still diverge,
// and the failure mode is the worst kind — every token silently rejected while both sides stay
// individually correct and individually green. So the duplicate is gone rather than guarded.
//
// **Client tokens are verified by the APP, which is also the only thing that mints them.** The gateway
// carries the presented credential through as an opaque string and never inspects it. One
// implementation, in `ClientRegistry`, so there is nothing to drift from.
//
// Two things fall out of that, both improvements rather than costs:
//
//   - **The root secret never leaves the app.** The stdin handover shrank from two secrets to one
//     precomputed string, and the thing that can mint credentials now exists in exactly one process.
//   - **The inbound envelope carries a CREDENTIAL, never a principal.** D4 planned to strip and
//     re-stamp a caller-supplied `principal_id` on every envelope; that field does not exist on the
//     inbound path at all now, so there is nothing to forge and nothing to remember to overwrite. The
//     app derives the principal from a credential it verified itself.
//
// What remains here is a routing decision the gateway genuinely has to make on its own: whether a peer
// is THE HOST, since the host is who every `/call` is forwarded to. That needs no format either — the
// app hands over the exact expected string and this compares against it.

// HostCredential is the one secret the gateway holds: the literal token that proves "I am the host".
//
// Regenerated by the app on EVERY gateway spawn and written nowhere, which is what makes `is_host`
// unforgeable by anything on disk — a stale host credential cannot outlive the app that minted it.
// Today the field is simply believed: any peer claiming `is_host: true` becomes `globalHostID`
// (gateway.go:283), which is the peer every call is routed to.
type HostCredential struct {
	expected string
}

// Configured reports whether the gateway can check host claims at all. A gateway launched by hand has
// no pipe and therefore no credential; it must serve channel routing only rather than pretend.
func (h HostCredential) Configured() bool { return h.expected != "" }

// Matches compares a presented credential in constant time.
//
// `subtle.ConstantTimeCompare` rather than `==` (NFR1): comparing a credential with `==` leaks how much
// of a forgery was correct through timing, which is enough to build one a byte at a time. It also
// returns 0 on a length mismatch, so an empty or truncated claim cannot pass.
func (h HostCredential) Matches(presented string) bool {
	if h.expected == "" || presented == "" {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(h.expected), []byte(presented)) == 1
}

// ReadHostCredential takes one line from the pipe the parent app already holds.
//
// **Over stdin, NOT the environment**, and that is measured rather than stylistic: `ps -E` returns a
// same-user process's full environment, so passing a secret at spawn that way would publish it to every
// process running as the user — the exact escalation this slice exists to close.
//
// Returns the SAME reader for the caller to continue with. This matters and is easy to get wrong: the
// EOF death-watch reads stdin after this, and resuming from `os.Stdin` instead of this buffered reader
// would discard whatever the buffer had already pulled in. Spike C's one carried detail.
func ReadHostCredential(stdin io.Reader) (HostCredential, *bufio.Reader) {
	r := bufio.NewReader(stdin)
	line, err := r.ReadString('\n')
	if err != nil && line == "" {
		return HostCredential{}, r
	}
	return HostCredential{expected: strings.TrimRight(line, "\r\n")}, r
}

// BearerToken pulls a credential out of an Authorization header value.
//
// Empty when absent or malformed — never an error, because "no credential" is an ordinary state on this
// door until enforcement lands, and because the gateway does not judge credentials: it forwards them.
func BearerToken(header string) string {
	const prefix = "Bearer "
	if len(header) <= len(prefix) || !strings.EqualFold(header[:len(prefix)], prefix) {
		return ""
	}
	return strings.TrimSpace(header[len(prefix):])
}
