package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"sync"
	"sync/atomic"
	"time"

	"nhooyr.io/websocket"
)

// THE DOOR, AND NOTHING ELSE (nautilus Phase 0 step 3, docs/plan-nautilus-phase0.md).
//
// This gateway does three things. It accepts the app's one host connection, proven by the per-spawn
// host credential. It forwards every call, from `/call` over HTTP or from a caller on `/ws`, to that
// host. And it carries the host's `response` and `stream` frames back to whoever asked.
//
// It used to be a messaging hub as well: channels, join tokens, presence, typing, read receipts,
// store-and-forward, an Apple sign-in challenge. None of that served a call, all of it shared the one
// connection the call door rides, and the app stopped speaking it in step 2. It is gone, and an
// envelope of any of those types is refused as unknown.

const (
	maxMessageSize   = 2 * 1024 * 1024 // 2 MB per WebSocket message (API responses can carry large payloads)
	maxPeerIDLen     = 128
	maxSenderNameLen = 256
	rateLimitPerSec  = 30 // frames per second per peer
)

// Envelope is the wire format between a peer and the gateway.
type Envelope struct {
	Type       string          `json:"type"`
	SenderID   string          `json:"sender_id,omitempty"`
	SenderName string          `json:"sender_name,omitempty"`
	PeerID     string          `json:"peer_id,omitempty"` // the peer that sent this, stamped by the gateway
	Payload    json.RawMessage `json:"payload,omitempty"`
	Timestamp  int64           `json:"timestamp,omitempty"`
	Error      string          `json:"error,omitempty"`
	// Code is the machine-readable form of Error, from the SAME list the app publishes
	// (`BridgeErrorCode`). See errorcodes.go. A remote caller meets these before anything the app says.
	Code string `json:"code,omitempty"`

	// The call: which method, with what, answered on which call id, back to whom.
	Method   string          `json:"method,omitempty"`
	Args     json.RawMessage `json:"args,omitempty"`
	CallID   string          `json:"call_id,omitempty"`
	TargetID string          `json:"target_id,omitempty"`

	IsHost bool `json:"is_host,omitempty"` // claimed by the Port42 app; proven by HostCredential
	// HostCredential proves an `is_host` claim. Generated by the app per gateway spawn and handed over
	// on stdin, so nothing on disk can forge it. Never logged (NFR2).
	HostCredential string `json:"host_credential,omitempty"`
	// Credential is a CLIENT's token, carried OPAQUELY. The gateway never parses or verifies it: the
	// app both mints and verifies, so the format has exactly one implementation and cannot drift.
	//
	// Note what is deliberately absent: there is no inbound `principal_id`. D4 planned to strip and
	// re-stamp one on every envelope; carrying a credential instead means there is nothing to forge
	// and nothing to remember to overwrite. The app derives the principal from what it verified itself.
	Credential string `json:"credential,omitempty"`

	// Streamable says the CALLER can receive mid-call `stream` frames, because there is a live peer
	// to route them back to. Set by `routeCall` on the WS door and never on `/call`: HTTP is
	// request/response, so a subscription there could only ever hang until the timeout, which is
	// exactly what it used to do.
	//
	// The app reads this to REFUSE a subscription it could not deliver, rather than accepting one it
	// will silently drop. A door that cannot stream should say so, not go quiet.
	Streamable bool `json:"streamable,omitempty"`
}

// Peer is one WebSocket connection: the app's host connection, or a caller.
type Peer struct {
	ID     string
	Name   string
	Conn   *websocket.Conn
	IsHost bool // true if this is the Port42 app
	// HostCredential as presented in `identify`, checked against the one the app handed over.
	HostCredential string
	// Credential is the CALLER's token as given once at `identify`, carried opaquely like every
	// credential here. Every call this peer sends carries it (see routeCall).
	Credential string
	mu         sync.Mutex
	// Rate limiting: sliding window of frame timestamps
	msgTimes []time.Time
	rateMu   sync.Mutex
}

// rateOK returns true if the peer hasn't exceeded the frame rate limit.
func (p *Peer) rateOK() bool {
	p.rateMu.Lock()
	defer p.rateMu.Unlock()
	now := time.Now()
	cutoff := now.Add(-time.Second)
	start := 0
	for start < len(p.msgTimes) && p.msgTimes[start].Before(cutoff) {
		start++
	}
	p.msgTimes = p.msgTimes[start:]
	if len(p.msgTimes) >= rateLimitPerSec {
		return false
	}
	p.msgTimes = append(p.msgTimes, now)
	return true
}

func (p *Peer) Send(ctx context.Context, env Envelope) error {
	data, err := json.Marshal(env)
	if err != nil {
		return err
	}
	p.mu.Lock()
	defer p.mu.Unlock()
	return p.Conn.Write(ctx, websocket.MessageText, data)
}

// Gateway holds the connected peers and routes calls to the host.
type Gateway struct {
	mu    sync.RWMutex
	peers map[string]*Peer
	// globalHostID is the peer ID of the Port42 app. Every call is forwarded to it.
	globalHostID string
	// httpCallbacks maps call_id -> reply channel for HandleHTTPCall
	httpCallbacks map[string]chan Envelope
	// httpCallSeq makes each HTTP call_id unique even when two calls land in the same nanosecond
	// (a UnixNano-only id collides under concurrency, dropping one response; the SenderID is the
	// fixed `local-http`, so the CallID is the only disambiguator).
	httpCallSeq uint64
	// hostCred is the credential an `is_host` claim must present, handed over by the app on stdin at
	// spawn. Zero value = not configured, which is the hand-launched gateway case.
	hostCred HostCredential
}

// SetHostCredential is called once, from the watch-parent goroutine, before any peer can identify.
func (g *Gateway) SetHostCredential(c HostCredential) {
	g.mu.Lock()
	defer g.mu.Unlock()
	g.hostCred = c
}

func (g *Gateway) hostCredentialConfigured() bool {
	g.mu.RLock()
	defer g.mu.RUnlock()
	return g.hostCred.Configured()
}

func (g *Gateway) hostCredentialMatches(presented string) bool {
	g.mu.RLock()
	defer g.mu.RUnlock()
	return g.hostCred.Matches(presented)
}

func NewGateway() *Gateway {
	return &Gateway{peers: make(map[string]*Peer)}
}

func (g *Gateway) HandleWebSocket(w http.ResponseWriter, req *http.Request) {
	conn, err := websocket.Accept(w, req, &websocket.AcceptOptions{
		OriginPatterns: []string{"*"},
	})
	if err != nil {
		log.Printf("[gateway] accept error: %v", err)
		return
	}
	defer conn.CloseNow()

	ctx := req.Context()

	// Tell the peer to identify. There is no challenge: the host proves itself with its credential,
	// and a caller's credential is verified by the app, never here.
	noAuthData, _ := json.Marshal(Envelope{Type: "no_auth"})
	conn.Write(ctx, websocket.MessageText, noAuthData)

	_, data, err := conn.Read(ctx)
	if err != nil {
		log.Printf("[gateway] read identify error: %v", err)
		return
	}

	var ident Envelope
	if err := json.Unmarshal(data, &ident); err != nil || ident.Type != "identify" || ident.SenderID == "" {
		conn.Close(websocket.StatusPolicyViolation, "first message must be identify with sender_id")
		return
	}
	if len(ident.SenderID) > maxPeerIDLen {
		conn.Close(websocket.StatusPolicyViolation, "sender_id too long")
		return
	}
	if len(ident.SenderName) > maxSenderNameLen {
		conn.Close(websocket.StatusPolicyViolation, "sender_name too long")
		return
	}

	peer := &Peer{
		ID:             ident.SenderID,
		Name:           ident.SenderName,
		Conn:           conn,
		IsHost:         ident.IsHost,
		HostCredential: ident.HostCredential,
		Credential:     ident.Credential,
	}

	g.addPeer(peer)
	defer g.removePeer(peer)

	// `is_host` NOW HAS TO BE PROVEN (slice-02 half two, D2/D8).
	//
	// It used to be believed: any peer claiming `is_host: true` became `globalHostID`, which is the
	// peer EVERY `/call` is forwarded to — so a claim was enough to intercept the whole bridge. It was
	// established from source rather than measured, because testing it live wedges the instance's
	// routing.
	//
	// The proof is a credential the app generates per gateway spawn, hands over on stdin, and stores
	// nowhere, so nothing on disk can forge it and a stale one cannot outlive the app that minted it.
	//
	// **When no credential was configured the claim is still honored**, deliberately: a gateway
	// launched by hand has no pipe, and refusing hosts there would break the relay case (BR2/BR3)
	// rather than close a hole. The credential is what an app-spawned gateway checks.
	if peer.IsHost {
		if g.hostCredentialConfigured() && !g.hostCredentialMatches(peer.HostCredential) {
			log.Printf("[gateway] REFUSED is_host claim from %s: credential missing or wrong",
				peer.ID[:min(8, len(peer.ID))])
		} else {
			g.mu.Lock()
			g.globalHostID = peer.ID
			g.mu.Unlock()
			log.Printf("[gateway] global host set: %s", peer.ID[:min(8, len(peer.ID))])
		}
	}

	log.Printf("[gateway] peer connected: %s", peer.ID)
	peer.Send(ctx, Envelope{Type: "welcome", SenderID: peer.ID})

	conn.SetReadLimit(maxMessageSize)

	for {
		_, data, err := conn.Read(ctx)
		if err != nil {
			if websocket.CloseStatus(err) != -1 {
				log.Printf("[gateway] peer %s disconnected: %v", peer.ID, websocket.CloseStatus(err))
			} else {
				log.Printf("[gateway] peer %s read error: %v", peer.ID, err)
			}
			return
		}

		if !peer.rateOK() {
			peer.Send(ctx, Envelope{Type: "error", Error: "rate limit exceeded"})
			log.Printf("[gateway] peer %s rate limited", peer.ID[:min(8, len(peer.ID))])
			continue
		}

		var env Envelope
		if err := json.Unmarshal(data, &env); err != nil {
			log.Printf("[gateway] peer %s bad json: %v", peer.ID[:min(8, len(peer.ID))], err)
			continue
		}
		// The frame's TYPE only. A call frame can carry a caller's credential, so its body is never
		// written to the log.
		log.Printf("[gateway] %s from %s", env.Type, peer.ID[:min(8, len(peer.ID))])

		env.PeerID = peer.ID
		if env.Timestamp == 0 {
			env.Timestamp = time.Now().UnixMilli()
		}

		switch env.Type {
		case "call":
			g.routeCall(ctx, peer, env)
		case "response":
			g.routeResponse(ctx, peer, env)
		case "stream":
			g.routeStream(ctx, peer, env)
		default:
			peer.Send(ctx, Envelope{Type: "error", Error: "unknown type: " + env.Type,
				Code: CodeUnknownMethod, CallID: env.CallID})
		}
	}
}

func (g *Gateway) addPeer(p *Peer) {
	g.mu.Lock()
	defer g.mu.Unlock()
	if old, ok := g.peers[p.ID]; ok {
		old.Conn.Close(websocket.StatusGoingAway, "replaced by new connection")
	}
	g.peers[p.ID] = p
}

func (g *Gateway) removePeer(p *Peer) {
	g.mu.Lock()
	defer g.mu.Unlock()
	if current, ok := g.peers[p.ID]; ok && current == p {
		delete(g.peers, p.ID)
	}
	if g.globalHostID == p.ID {
		g.globalHostID = ""
	}
}

func (g *Gateway) HandleHTTPCall(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost && r.Method != http.MethodGet {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}

	var req struct {
		Method string          `json:"method"`
		Args   json.RawMessage `json:"args"`
	}
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil || req.Method == "" {
		http.Error(w, `{"error":"missing method","code":"`+CodeMissingArg+`"}`, http.StatusBadRequest)
		return
	}

	g.mu.RLock()
	hostID := g.globalHostID
	g.mu.RUnlock()
	if hostID == "" {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusServiceUnavailable)
		json.NewEncoder(w).Encode(map[string]string{
			"error": "no host available — is Port42 running?", "code": CodeNoHost})
		return
	}

	g.mu.RLock()
	hostPeer, online := g.peers[hostID]
	g.mu.RUnlock()
	if !online {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusServiceUnavailable)
		json.NewEncoder(w).Encode(map[string]string{"error": "host is offline"})
		return
	}

	callID := fmt.Sprintf("http-%d-%d", time.Now().UnixNano(), atomic.AddUint64(&g.httpCallSeq, 1))
	replyCh := make(chan Envelope, 1)

	g.mu.Lock()
	if g.httpCallbacks == nil {
		g.httpCallbacks = make(map[string]chan Envelope)
	}
	g.httpCallbacks[callID] = replyCh
	g.mu.Unlock()

	defer func() {
		g.mu.Lock()
		delete(g.httpCallbacks, callID)
		g.mu.Unlock()
	}()

	args := req.Args
	if len(args) == 0 {
		args = json.RawMessage(`{}`)
	}

	// `local-http` IS DEAD AS AN IDENTITY (5b) and survives here as a ROUTING ADDRESS ONLY.
	//
	// It used to be the shared, unauthenticated principal every local process collapsed into, which
	// is why a permission card was anonymous and why a grant given to one tool was inherited by every
	// other. **The app now refuses a call that carries no credential**, and a caller's identity comes
	// from that credential in exactly one place (`AppState.resolveGatewayCaller`). Nothing anywhere
	// authorizes on `sender_id`.
	//
	// So this constant is inert, and it is kept rather than removed because `sender_id` is a required
	// envelope field with a real job on this door: it labels the HTTP caller for routing. Response
	// routing keys on CallID, not SenderID.
	//
	// **If you are here adding a peer at slice-02's wire half: do not thread a peer identity through
	// this field.** An identity is formed from a credential by the app, and adding a second place it
	// can be formed is the exact defect 5a and 5b closed.
	const localPrincipalID = "local-http"

	// The credential rides `Authorization: Bearer`, because the WebSocket API cannot set request
	// headers and `identify` is the only place available on that door — so the two doors differ in
	// where a credential sits and in nothing else.
	//
	// Carried OPAQUELY: the gateway does not parse or verify it. The app mints and verifies, so the
	// token format has exactly one implementation and cannot drift between two languages.
	call := Envelope{
		Type:       "call",
		Method:     req.Method,
		Args:       args,
		CallID:     callID,
		SenderID:   localPrincipalID,
		Credential: BearerToken(r.Header.Get("Authorization")),
	}

	ctx := r.Context()
	if err := hostPeer.Send(ctx, call); err != nil {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusInternalServerError)
		json.NewEncoder(w).Encode(map[string]string{
			"error": "failed to reach host", "code": CodeTransportFailed})
		return
	}

	// Wait for response (30s timeout)
	select {
	case resp := <-replyCh:
		w.Header().Set("Content-Type", "application/json")
		if resp.Error != "" {
			w.WriteHeader(http.StatusBadGateway)
			json.NewEncoder(w).Encode(map[string]string{"error": resp.Error})
		} else if resp.Payload != nil {
			var payload map[string]interface{}
			if err := json.Unmarshal(resp.Payload, &payload); err == nil {
				json.NewEncoder(w).Encode(payload)
			} else {
				w.Write(resp.Payload)
			}
		} else {
			json.NewEncoder(w).Encode(map[string]string{"content": ""})
		}
	case <-time.After(30 * time.Second):
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusGatewayTimeout)
		json.NewEncoder(w).Encode(map[string]string{
			"error": "timeout waiting for host response", "code": CodeTimedOut})
	case <-ctx.Done():
		// Client disconnected
	}
}

// routeCall forwards a WebSocket caller's call to the host.
func (g *Gateway) routeCall(ctx context.Context, sender *Peer, env Envelope) {
	g.mu.RLock()
	hostID := g.globalHostID
	hostPeer, online := g.peers[hostID]
	g.mu.RUnlock()

	if hostID == "" {
		sender.Send(ctx, Envelope{Type: "error", Error: "no host available", Code: CodeNoHost, CallID: env.CallID})
		return
	}
	if !online {
		sender.Send(ctx, Envelope{Type: "error", Error: "host is offline", Code: CodeHostOffline, CallID: env.CallID})
		return
	}

	// Forward the call to the host, ensuring SenderID is set so host knows where to reply.
	//
	// A WS caller is a live peer, so mid-call `stream` frames have somewhere to go. That is the whole
	// difference from the HTTP door, and it is set HERE rather than trusted from the caller: a client
	// cannot ask to be streamable on a transport that cannot carry it.
	env.SenderID = sender.ID
	env.Streamable = true
	// A CONNECTION IS ONE CALLER (nautilus Phase 0 step 4). The credential given at `identify` goes on
	// every call this peer sends, REPLACING whatever the envelope carries: one connection, one
	// identity, set once. Before this, a WS caller had to repeat its token on every envelope, and
	// the browser guest, which gives it once, had its live subscription refused (audit F2).
	env.Credential = sender.Credential
	if err := hostPeer.Send(ctx, env); err != nil {
		log.Printf("[gateway] failed to send call to host %s: %v", hostID, err)
		sender.Send(ctx, Envelope{Type: "error", Error: "failed to reach host", Code: CodeTransportFailed, CallID: env.CallID})
	}
}

// routeStream forwards ONE event of an in-flight streaming call back to its caller.
//
// It is a `response` that does not end the call. The difference matters and is the whole reason this
// exists: before it, `RemoteToolExecutor` served every streaming method with a yield closure that
// THREW EACH EVENT AWAY, and the gateway had no frame that could have carried one anyway. So a
// caller subscribing to a port received nothing, forever, on either door.
//
// Deliberately NOT consulted against `httpCallbacks`: an HTTP call is request/response and must be
// completed by exactly one `response`. A stream frame that resolved that callback would truncate the
// call at its first event. HTTP callers are refused a subscription up front instead (see Streamable).
func (g *Gateway) routeStream(ctx context.Context, sender *Peer, env Envelope) {
	if env.TargetID == "" {
		log.Printf("[gateway] stream from %s missing target_id", sender.ID)
		return
	}

	g.mu.RLock()
	targetPeer, online := g.peers[env.TargetID]
	g.mu.RUnlock()

	// A subscriber that went away is not an error: the call is torn down by the disconnect, and the
	// producer stops when its task is cancelled. Dropping quietly is correct.
	if !online {
		return
	}
	if err := targetPeer.Send(ctx, env); err != nil {
		log.Printf("[gateway] failed to stream to %s: %v", env.TargetID, err)
	}
}

func (g *Gateway) routeResponse(ctx context.Context, sender *Peer, env Envelope) {
	if env.TargetID == "" {
		log.Printf("[gateway] response from %s missing target_id", sender.ID)
		return
	}

	// Check if this is a reply to an HTTP /call request
	g.mu.Lock()
	if ch, ok := g.httpCallbacks[env.CallID]; ok {
		delete(g.httpCallbacks, env.CallID)
		g.mu.Unlock()
		select {
		case ch <- env:
		default:
		}
		return
	}
	g.mu.Unlock()

	g.mu.RLock()
	targetPeer, online := g.peers[env.TargetID]
	g.mu.RUnlock()

	if !online {
		log.Printf("[gateway] response target %s is offline", env.TargetID)
		return
	}

	// Forward response back to the original caller
	if err := targetPeer.Send(ctx, env); err != nil {
		log.Printf("[gateway] failed to send response to %s: %v", env.TargetID, err)
	}
}
