import Foundation
import GRDB

// MARK: - JSON Value (Codable Any)

/// Codable wrapper for arbitrary JSON values so RPC call args can carry full JSON objects.
enum JSONValue: Codable {
    case string(String)
    case number(Double)
    case bool(Bool)
    case null
    case array([JSONValue])
    case object([String: JSONValue])

    var anyValue: Any {
        switch self {
        case .string(let s): return s
        case .number(let n): return n
        case .bool(let b): return b
        case .null: return NSNull()
        case .array(let a): return a.map(\.anyValue)
        case .object(let o): return o.mapValues(\.anyValue)
        }
    }

    init(from decoder: Decoder) throws {
        let c = try decoder.singleValueContainer()
        if c.decodeNil() { self = .null }
        else if let b = try? c.decode(Bool.self) { self = .bool(b) }
        else if let n = try? c.decode(Double.self) { self = .number(n) }
        else if let s = try? c.decode(String.self) { self = .string(s) }
        else if let a = try? c.decode([JSONValue].self) { self = .array(a) }
        else if let o = try? c.decode([String: JSONValue].self) { self = .object(o) }
        else { throw DecodingError.dataCorrupted(.init(codingPath: decoder.codingPath, debugDescription: "Undecodable JSON value")) }
    }

    func encode(to encoder: Encoder) throws {
        var c = encoder.singleValueContainer()
        switch self {
        case .string(let s): try c.encode(s)
        case .number(let n): try c.encode(n)
        case .bool(let b): try c.encode(b)
        case .null: try c.encodeNil()
        case .array(let a): try c.encode(a)
        case .object(let o): try c.encode(o)
        }
    }
}

// MARK: - Sync Wire Format

struct SyncEnvelope: Codable {
    let type: String
    var spaceId: String?
    var senderId: String?
    var senderName: String?
    var peerId: String?
    var messageId: String?
    var payload: SyncPayload?
    var timestamp: Int64?
    var error: String?
    var token: String?
    // Presence fields
    var onlineIds: [String]?
    var status: String?
    var companionIds: [String]?
    // Auth fields (F-511)
    var nonce: String?
    var identityToken: String?
    var authType: String?
    var isHost: Bool?
    /// Proves an `is_host` claim (slice-02 half two, D2). Generated by the app per gateway spawn and
    /// handed to the gateway on stdin, so nothing on disk can forge it — where previously the claim was
    /// simply believed, and whoever made it became the peer every `/call` was routed to.
    var hostCredential: String?
    /// A CLIENT's token, carried opaquely from the gateway. The app verifies it (it is also the only
    /// thing that mints one), so the format has a single implementation and cannot drift.
    var credential: String?

    /// Set by the GATEWAY on the WS door only: this caller is a live peer, so mid-call `stream`
    /// frames can reach it. Absent on `/call`, which is request/response.
    var streamable: Bool?

    // RPC fields
    var method: String?
    var args: [String: JSONValue]?   // JSON object — maps directly to ToolExecutor input
    var callId: String?
    var targetId: String?

    /// Unwrap args into [String: Any] for passing to ToolExecutor.
    var argsAsAny: [String: Any] { args?.mapValues(\.anyValue) ?? [:] }

    enum CodingKeys: String, CodingKey {
        case type
        case spaceId = "channel_id"
        case senderId = "sender_id"
        case senderName = "sender_name"
        case peerId = "peer_id"
        case messageId = "message_id"
        case payload
        case timestamp
        case error
        case token
        case onlineIds = "online_ids"
        case status
        case companionIds = "companion_ids"
        case nonce
        case identityToken = "identity_token"
        case authType = "auth_type"
        case isHost = "is_host"
        case hostCredential = "host_credential"
        case credential
        case method
        case args
        case callId = "call_id"
        case targetId = "target_id"
        // MUST be listed. `CodingKeys` here is explicit, so a property left out of it is silently
        // never decoded — it compiles, it runs, and the value is always nil. That is how the first
        // build of this flag turned a WS caller into an HTTP one and refused a subscription on the
        // door that supports it.
        case streamable
    }
}

public struct SyncPayload: Codable {
    public let senderName: String
    public let senderType: String
    public let content: String
    public let replyToId: String?
    /// When true, `content` is an encrypted blob and senderName is masked.
    public var encrypted: Bool?
    /// Display name of the human who owns this sender (nil for human senders).
    public var senderOwner: String?

    public init(senderName: String, senderType: String, content: String, replyToId: String?, encrypted: Bool? = nil, senderOwner: String? = nil) {
        self.senderName = senderName
        self.senderType = senderType
        self.content = content
        self.replyToId = replyToId
        self.encrypted = encrypted
        self.senderOwner = senderOwner
    }
}

// MARK: - Sync Service

@MainActor
public final class SyncService: NSObject, ObservableObject {
    @Published public var isConnected = false
    @Published public var gatewayURL: String?
    /// Online user IDs per space
    @Published public var onlineUsers: [String: Set<String>] = [:]
    /// Remote typing indicators: spaceId -> set of sender names currently typing
    @Published public var remoteTypingNames: [String: Set<String>] = [:]
    /// Cached display names from presence events: userId -> displayName
    @Published public var knownNames: [String: String] = [:]

    private var webSocket: URLSessionWebSocketTask?
    private var urlSession: URLSession?
    private var userId: String?
    private var userName: String?
    private weak var db: DatabaseService?
    private var joinedSpaces: Set<String> = []
    private var reconnectTask: Task<Void, Never>?
    private var shouldReconnect = false
    private var didSendIdentify = false
    /// Pending token request continuations: spaceId -> continuation
    private var tokenContinuations: [String: CheckedContinuation<String, Error>] = [:]
    /// Apple auth service for remote gateway authentication
    private var appleAuth: AppleAuthService?
    /// Stored Apple user ID for silent re-auth
    private var appleUserID: String?

    /// Called when a message arrives from the network (spaceId, message)
    public var onMessageReceived: ((String, Message) -> Void)?
    /// Called when a peer's presence changes (spaceId, senderId, senderName, status "online"/"offline")
    public var onPresenceChanged: ((String, String, String?, String) -> Void)?
    /// Set to true only for the primary Port42 app so the gateway registers it as the RPC host.
    /// CLI tools and other peers must leave this false.
    public var actAsHost: Bool = false

    /// Called when a remote call is received (senderId, callId, method, input) -> responsePayload
    /// `(senderId, callId, method, input, credential)`.
    ///
    /// The CREDENTIAL is the fifth argument and the reason this signature changed: `senderId` addresses
    /// and must never authorize, so the thing that decides WHO a caller is has to travel separately
    /// from the thing that says where to send the reply. The app verifies it — it is also the only
    /// thing that mints one — so the token format has a single implementation.
    /// The gateway handed us a call. The last parameter is how a STREAMING method emits before it
    /// finishes: nil when the caller's door cannot carry mid-call frames, so the method can refuse
    /// rather than emit into nothing.
    public var onCallReceived: (@MainActor (String, String, String, [String: Any], String?,
                                            (@MainActor (Any) -> Void)?) async -> Any)?
    /// Called when a response to our own call arrives
    public var onResponseReceived: ((String, Any) -> Void)?

    /// Pending outgoing calls: callId -> continuation
    private var pendingCalls: [String: CheckedContinuation<Any, Error>] = [:]

    public func configure(gatewayURL: String, userId: String, userName: String? = nil, db: DatabaseService, appleAuth: AppleAuthService? = nil, appleUserID: String? = nil) {
        self.gatewayURL = gatewayURL
        self.userId = userId
        self.userName = userName
        self.db = db
        self.appleAuth = appleAuth
        self.appleUserID = appleUserID
    }

    /// Returns true if the gateway URL points to localhost (skip auth).
    nonisolated static func isLocalGateway(_ url: String) -> Bool {
        url.contains("localhost") || url.contains("127.0.0.1")
    }

    public func connect() {
        guard let gatewayURL, let url = URL(string: gatewayURL + "/ws") else {
            print("[sync] no gateway URL configured")
            return
        }
        guard let userId else {
            print("[sync] no user ID")
            return
        }

        disconnect(reconnect: false)
        shouldReconnect = true

        let session = URLSession(configuration: .default, delegate: self, delegateQueue: nil)
        self.urlSession = session

        var request = URLRequest(url: url)
        // Skip ngrok's free-tier browser warning interstitial
        request.setValue("true", forHTTPHeaderField: "ngrok-skip-browser-warning")
        let task = session.webSocketTask(with: request)
        self.webSocket = task
        task.resume()

        let isLocal = Self.isLocalGateway(gatewayURL)

        didSendIdentify = false
        if isLocal {
            // Localhost: send identify immediately (no challenge expected)
            let identify = SyncEnvelope(type: "identify", senderId: userId, senderName: userName, isHost: actAsHost,
                                     hostCredential: GatewayProcess.shared.hostCredential)
            send(identify)
            didSendIdentify = true
        }
        // Remote: wait for challenge message in receiveLoop, then send identify

        // Start receive loop
        receiveLoop()

        print("[sync] connecting to \(gatewayURL) (local=\(isLocal))")
    }

    public func disconnect(reconnect: Bool = false) {
        if !reconnect {
            shouldReconnect = false
        }
        reconnectTask?.cancel()
        reconnectTask = nil
        webSocket?.cancel(with: .normalClosure, reason: nil)
        webSocket = nil
        urlSession?.invalidateAndCancel()
        urlSession = nil
        isConnected = false
        onlineUsers = [:]
        knownNames = [:]
    }

    // MARK: - Space Management

    /// Companion IDs per space, sent to gateway on join for cross-instance presence
    private var spaceCompanions: [String: [String]] = [:]

    /// Tokens received from the gateway for space joins (persisted across reconnects)
    private var spaceTokens: [String: String] = [:]

    public func joinSpace(_ spaceId: String, companionIds: [String] = [], token: String? = nil) {
        let alreadyJoined = joinedSpaces.contains(spaceId)
        spaceCompanions[spaceId] = companionIds
        if let token { spaceTokens[spaceId] = token }
        joinedSpaces.insert(spaceId)
        guard isConnected else { return }
        // Skip sending join if already joined (prevents duplicate presence broadcasts)
        guard !alreadyJoined else { return }
        var envelope = SyncEnvelope(type: "join", spaceId: spaceId, companionIds: companionIds.isEmpty ? nil : companionIds)
        envelope.token = spaceTokens[spaceId]
        send(envelope)
    }

    public func leaveSpace(_ spaceId: String) {
        joinedSpaces.remove(spaceId)
        guard isConnected else { return }
        send(SyncEnvelope(type: "leave", spaceId: spaceId))
    }

    public func joinAllSpaces() {
        for spaceId in joinedSpaces {
            let companions = spaceCompanions[spaceId]
            var envelope = SyncEnvelope(type: "join", spaceId: spaceId, companionIds: companions?.isEmpty == false ? companions : nil)
            envelope.token = spaceTokens[spaceId]
            send(envelope)
        }
    }

    // MARK: - Send Message

    public func sendMessage(_ message: Message) {
        let clearPayload = SyncPayload(
            senderName: message.senderName,
            senderType: message.senderType,
            content: message.content,
            replyToId: message.replyToId,
            senderOwner: message.senderOwner
        )

        let payload: SyncPayload
        if let key = try? db?.getSpaceKey(spaceId: message.spaceId),
           let blob = SpaceCrypto.encrypt(clearPayload, keyBase64: key) {
            // Encrypted: content is the blob, senderName masked
            payload = SyncPayload(
                senderName: "",
                senderType: message.senderType,
                content: blob,
                replyToId: nil,
                encrypted: true
            )
        } else {
            // No key or encryption failed: send plaintext (backward compat)
            payload = clearPayload
        }

        let envelope = SyncEnvelope(
            type: "message",
            spaceId: message.spaceId,
            senderId: message.senderId,
            messageId: message.id,
            payload: payload,
            timestamp: Int64(message.timestamp.timeIntervalSince1970 * 1000)
        )

        send(envelope)
    }

    /// Broadcast typing indicator to other peers
    public func sendTyping(spaceId: String, senderName: String, isTyping: Bool, senderOwner: String? = nil) {
        let envelope = SyncEnvelope(
            type: "typing",
            spaceId: spaceId,
            payload: SyncPayload(
                senderName: senderName,
                senderType: "agent",
                content: isTyping ? "typing" : "stopped",
                replyToId: nil,
                senderOwner: senderOwner
            )
        )
        print("[sync] sendTyping: \(senderName) isTyping=\(isTyping) space=\(spaceId)")
        send(envelope)
    }

    /// Request a single-use join token for a space from the gateway.
    public func requestToken(spaceId: String) async throws -> String {
        return try await withCheckedThrowingContinuation { continuation in
            tokenContinuations[spaceId] = continuation
            send(SyncEnvelope(type: "create_token", spaceId: spaceId))
        }
    }

    // MARK: - Private

    private func send(_ envelope: SyncEnvelope) {
        guard let data = try? JSONEncoder().encode(envelope),
              let text = String(data: data, encoding: .utf8) else { return }

        webSocket?.send(.string(text)) { error in
            if let error {
                NSLog("[sync] send error: \(error)")
            }
        }
    }

    private func receiveLoop() {
        guard let ws = webSocket else { return }
        ws.receive { [weak self] result in
            Task { @MainActor in
                guard let self else { return }
                // Ignore callbacks from stale WebSocket connections
                guard ws === self.webSocket else { return }

                switch result {
                case .success(let message):
                    switch message {
                    case .string(let text):
                        self.handleMessage(text)
                    case .data(let data):
                        if let text = String(data: data, encoding: .utf8) {
                            self.handleMessage(text)
                        }
                    @unknown default:
                        break
                    }
                    // Continue receiving
                    self.receiveLoop()

                case .failure(let error):
                    NSLog("[sync] receive error: \(error)")
                    self.isConnected = false
                    self.scheduleReconnect()
                }
            }
        }
    }

    private func handleMessage(_ text: String) {
        guard let data = text.data(using: .utf8),
              let envelope = try? JSONDecoder().decode(SyncEnvelope.self, from: data) else {
            print("[sync] failed to decode message")
            return
        }

        switch envelope.type {
        case "challenge":
            handleChallenge(envelope)

        case "no_auth":
            // Gateway has no auth, send identify (skip if already sent for local connections)
            if !didSendIdentify, let userId {
                send(SyncEnvelope(type: "identify", senderId: userId, senderName: userName, isHost: actAsHost,
                                     hostCredential: GatewayProcess.shared.hostCredential))
                print("[sync] sent identify (no auth required)")
            }

        case "welcome":
            print("[sync] connected as \(envelope.senderId ?? "?")")
            isConnected = true
            onlineUsers = [:] // Reset on reconnect
            joinAllSpaces()

        case "message":
            handleIncomingMessage(envelope)

        case "history":
            handleHistoryMessage(envelope)

        case "ack":
            handleAck(envelope)

        case "delivered":
            handleDelivered(envelope)

        case "read":
            handleReadReceipt(envelope)

        case "presence":
            handlePresence(envelope)

        case "typing":
            handleTyping(envelope)

        case "token":
            handleToken(envelope)

        case "call":
            handleCall(envelope)

        case "response":
            handleResponse(envelope)

        case "error":
            print("[sync] gateway error: \(envelope.error ?? "unknown")")
            // Check if this error is for a pending token request
            if let spaceId = envelope.spaceId,
               let continuation = tokenContinuations.removeValue(forKey: spaceId) {
                continuation.resume(throwing: NSError(domain: "SyncService", code: -1,
                    userInfo: [NSLocalizedDescriptionKey: envelope.error ?? "unknown error"]))
            }

        default:
            break
        }
    }

    private func handleIncomingMessage(_ envelope: SyncEnvelope) {
        guard let spaceId = envelope.spaceId,
              let senderId = envelope.senderId,
              let messageId = envelope.messageId,
              let payload = envelope.payload else {
            print("[sync] incomplete message envelope")
            return
        }

        // Don't insert our own messages (use authenticated peerId from gateway)
        let authenticatedPeer = envelope.peerId ?? senderId
        guard authenticatedPeer != userId else { return }

        // Decrypt if encrypted
        let resolvedPayload: SyncPayload
        if payload.encrypted == true {
            guard let key = try? db?.getSpaceKey(spaceId: spaceId),
                  let decrypted = SpaceCrypto.decrypt(blob: payload.content, keyBase64: key) else {
                NSLog("[sync] failed to decrypt message %@ in space %@", messageId, spaceId)
                return
            }
            resolvedPayload = decrypted
        } else {
            resolvedPayload = payload
        }

        let timestamp: Date
        if let ts = envelope.timestamp {
            timestamp = Date(timeIntervalSince1970: Double(ts) / 1000.0)
        } else {
            timestamp = Date()
        }

        let message = Message(
            id: messageId,
            spaceId: spaceId,
            senderId: senderId,
            senderName: resolvedPayload.senderName,
            senderType: resolvedPayload.senderType,
            content: resolvedPayload.content,
            timestamp: timestamp,
            replyToId: resolvedPayload.replyToId,
            syncStatus: "synced",
            createdAt: Date(),
            senderOwner: resolvedPayload.senderOwner
        )

        do {
            try db?.saveMessage(message)
            print("[sync] received message from \(resolvedPayload.senderName) in space \(spaceId)")
            onMessageReceived?(spaceId, message)
        } catch {
            print("[sync] failed to save incoming message: \(error)")
        }
    }

    private func handleHistoryMessage(_ envelope: SyncEnvelope) {
        guard let spaceId = envelope.spaceId,
              let senderId = envelope.senderId,
              let messageId = envelope.messageId,
              let payload = envelope.payload else {
            return
        }

        // Decrypt if encrypted
        let resolvedPayload: SyncPayload
        if payload.encrypted == true {
            guard let key = try? db?.getSpaceKey(spaceId: spaceId),
                  let decrypted = SpaceCrypto.decrypt(blob: payload.content, keyBase64: key) else {
                return
            }
            resolvedPayload = decrypted
        } else {
            resolvedPayload = payload
        }

        let timestamp: Date
        if let ts = envelope.timestamp {
            timestamp = Date(timeIntervalSince1970: Double(ts) / 1000.0)
        } else {
            timestamp = Date()
        }

        let message = Message(
            id: messageId,
            spaceId: spaceId,
            senderId: senderId,
            senderName: resolvedPayload.senderName,
            senderType: resolvedPayload.senderType,
            content: resolvedPayload.content,
            timestamp: timestamp,
            replyToId: resolvedPayload.replyToId,
            syncStatus: "synced",
            createdAt: Date(),
            senderOwner: resolvedPayload.senderOwner
        )

        do {
            let inserted = try db?.saveMessageIfNotExists(message) ?? false
            if inserted {
                print("[sync] history: restored message from \(resolvedPayload.senderName)")
            }
        } catch {
            print("[sync] failed to save history message: \(error)")
        }
    }

    private func handleAck(_ envelope: SyncEnvelope) {
        guard let messageId = envelope.messageId else { return }
        do {
            try db?.updateSyncStatus(messageId: messageId, status: "synced")
        } catch {
            print("[sync] failed to update sync status: \(error)")
        }
    }

    private func handleDelivered(_ envelope: SyncEnvelope) {
        guard let messageId = envelope.messageId else { return }
        do {
            // Only upgrade from synced to delivered (don't downgrade from read)
            try db?.updateSyncStatusIfBefore(messageId: messageId, newStatus: "delivered", before: ["local", "synced"])
        } catch {
            print("[sync] failed to update delivered status: \(error)")
        }
    }

    private func handleReadReceipt(_ envelope: SyncEnvelope) {
        guard let spaceId = envelope.spaceId,
              let senderId = envelope.senderId,
              senderId != userId else { return }
        // Mark all our messages in this space as read
        do {
            try db?.markMessagesAsRead(spaceId: spaceId, bySenderId: userId ?? "")
        } catch {
            print("[sync] failed to update read status: \(error)")
        }
    }

    /// Send a read receipt for a space (call when user views messages)
    public func sendReadReceipt(spaceId: String) {
        send(SyncEnvelope(type: "read", spaceId: spaceId, senderId: userId))
    }

    private func handlePresence(_ envelope: SyncEnvelope) {
        guard let spaceId = envelope.spaceId else { return }

        if let onlineIds = envelope.onlineIds {
            // Full presence list (sent on join)
            onlineUsers[spaceId] = Set(onlineIds)
            print("[sync] presence for \(spaceId): \(onlineIds.count) online")
        } else if let senderId = envelope.senderId, let status = envelope.status {
            // Skip our own presence events
            guard senderId != userId else { return }
            // Cache display name from presence
            if let name = envelope.senderName, !name.isEmpty {
                knownNames[senderId] = name
            }
            // Single user update
            var members = onlineUsers[spaceId] ?? []
            if status == "online" {
                // Evict any stale entry with the same display name (reconnect with new peer ID)
                if let name = envelope.senderName, !name.isEmpty {
                    let stale = members.filter { knownNames[$0] == name && $0 != senderId }
                    stale.forEach { members.remove($0) }
                }
                members.insert(senderId)
            } else {
                members.remove(senderId)
            }
            onlineUsers[spaceId] = members
            let name = envelope.senderName
            print("[sync] \(name ?? senderId) went \(status) in \(spaceId)")
            onPresenceChanged?(spaceId, senderId, name, status)
        }
    }

    private func handleTyping(_ envelope: SyncEnvelope) {
        guard let spaceId = envelope.spaceId,
              let senderName = envelope.payload?.senderName,
              let content = envelope.payload?.content else { return }

        let displayName: String
        if let owner = envelope.payload?.senderOwner {
            displayName = "\(senderName)@\(owner)"
        } else {
            displayName = senderName
        }

        if content == "typing" {
            var names = remoteTypingNames[spaceId] ?? []
            names.insert(displayName)
            remoteTypingNames[spaceId] = names
            print("[sync] typing: \(displayName) in \(spaceId)")
        } else {
            remoteTypingNames[spaceId]?.remove(displayName)
        }
    }

    private func handleChallenge(_ envelope: SyncEnvelope) {
        guard let nonce = envelope.nonce else {
            print("[sync] challenge missing nonce")
            return
        }
        guard let userId else { return }

        Task {
            do {
                var token: String?
                if let appleAuth, let appleUserID {
                    // Silent re-auth with stored Apple user ID
                    token = try await appleAuth.silentAuth(appleUserID: appleUserID, nonce: nonce)
                } else if let appleAuth {
                    // First auth (shouldn't normally happen here, setup should have stored it)
                    let result = try await appleAuth.authenticate(nonce: nonce)
                    token = result.identityToken
                    self.appleUserID = result.appleUserID
                }

                if let token {
                    send(SyncEnvelope(
                        type: "identify",
                        senderId: userId,
                        senderName: userName,
                        identityToken: token,
                        authType: "apple",
                        isHost: actAsHost,
                                     hostCredential: GatewayProcess.shared.hostCredential
                    ))
                    print("[sync] sent authenticated identify")
                } else {
                    // No Apple auth available, send identify without token
                    send(SyncEnvelope(type: "identify", senderId: userId, senderName: userName, isHost: actAsHost,
                                     hostCredential: GatewayProcess.shared.hostCredential))
                    print("[sync] sent unauthenticated identify (no Apple auth)")
                }
            } catch {
                print("[sync] Apple auth failed: \(error), connecting without auth")
                send(SyncEnvelope(type: "identify", senderId: userId, senderName: userName, isHost: actAsHost,
                                     hostCredential: GatewayProcess.shared.hostCredential))
            }
        }
    }

    private func handleToken(_ envelope: SyncEnvelope) {
        guard let spaceId = envelope.spaceId,
              let token = envelope.token else { return }
        if let continuation = tokenContinuations.removeValue(forKey: spaceId) {
            continuation.resume(returning: token)
        }
        print("[sync] received join token for space \(spaceId)")
    }

    private func handleCall(_ envelope: SyncEnvelope) {
        guard let callId = envelope.callId,
              let method = envelope.method,
              let senderId = envelope.senderId else { return }

        print("[sync] received call from \(senderId): \(method) (id=\(callId))")

        Task { @MainActor in
            let input = envelope.argsAsAny
            let result: Any

            // A streaming method emits through here, as `stream` frames carrying the same call_id.
            // Only when the gateway said this door can carry them: on `/call` the value is nil and
            // the method is refused up front, which is better than the old behavior of accepting a
            // subscription and dropping every event of it.
            var emit: (@MainActor (Any) -> Void)?
            if envelope.streamable == true {
                emit = { [weak self] event in
                    guard let self else { return }
                    var frame = SyncEnvelope(type: "stream")
                    frame.callId = callId
                    frame.targetId = senderId
                    frame.payload = SyncPayload(senderName: "host", senderType: "host",
                                                content: SyncService.jsonContent(from: event),
                                                replyToId: nil)
                    self.send(frame)
                }
            }

            if let handler = onCallReceived {
                result = await handler(senderId, callId, method, input, envelope.credential, emit)
            } else {
                result = ["error": "method not implemented", "code": BridgeErrorCode.unsupported.wire] as [String: String]
            }

            // Send response back
            var resp = SyncEnvelope(type: "response")
            resp.callId = callId
            resp.targetId = senderId

            // Wrap result as JSON. .fragmentsAllowed: a registry method can return a bare
            // number/bool; without it JSONSerialization raises an ObjC NSException that `try?`
            // cannot catch, which wedges the main queue permanently (see PortBridge resolve).
            resp.payload = SyncPayload(senderName: "host", senderType: "host",
                                       content: Self.jsonContent(from: result), replyToId: nil)

            send(resp)
        }
    }

    /// One encoder for a call's RESULT and for each of its stream FRAMES, so a subscriber parses
    /// both the same way.
    ///
    /// `.fragmentsAllowed`: a registry method can return a bare number or bool, and without it
    /// JSONSerialization raises an ObjC NSException that `try?` cannot catch, which wedges the main
    /// queue permanently (see PortBridge resolve).
    static func jsonContent(from value: Any) -> String {
        if let str = value as? String { return str }
        if let data = try? JSONSerialization.data(withJSONObject: value, options: [.fragmentsAllowed]),
           let json = String(data: data, encoding: .utf8) { return json }
        return "{\"error\":\"unserializable result\"}"
    }

    private func handleResponse(_ envelope: SyncEnvelope) {
        guard let callId = envelope.callId else { return }
        print("[sync] received response for call \(callId)")

        if let continuation = pendingCalls.removeValue(forKey: callId) {
            if let payload = envelope.payload {
                // Parse content as JSON if possible
                if let data = payload.content.data(using: .utf8),
                   let json = try? JSONSerialization.jsonObject(with: data) {
                    continuation.resume(returning: json)
                } else {
                    continuation.resume(returning: payload.content)
                }
            } else {
                continuation.resume(returning: NSNull())
            }
        } else {
            // If no continuation, maybe it's a stream event or similar
            if let payload = envelope.payload {
                onResponseReceived?(callId, payload.content)
            }
        }
    }

    private func scheduleReconnect() {
        guard shouldReconnect else { return }
        reconnectTask?.cancel()
        reconnectTask = Task { @MainActor in
            try? await Task.sleep(nanoseconds: 3_000_000_000) // 3 seconds
            guard !Task.isCancelled, shouldReconnect else { return }
            print("[sync] reconnecting...")
            connect()
        }
    }
}

// MARK: - URLSessionWebSocketDelegate

extension SyncService: URLSessionWebSocketDelegate {
    nonisolated public func urlSession(
        _ session: URLSession,
        webSocketTask: URLSessionWebSocketTask,
        didOpenWithProtocol protocol: String?
    ) {
        Task { @MainActor in
            print("[sync] WebSocket opened to \(self.gatewayURL ?? "unknown")")
        }
    }

    nonisolated public func urlSession(
        _ session: URLSession,
        webSocketTask: URLSessionWebSocketTask,
        didCloseWith closeCode: URLSessionWebSocketTask.CloseCode,
        reason: Data?
    ) {
        let reasonStr = reason.flatMap { String(data: $0, encoding: .utf8) }
        Task { @MainActor in
            // Only reconnect if this is still the active WebSocket (not a stale one
            // being replaced by a new connect() call)
            guard webSocketTask === self.webSocket else {
                print("[sync] WebSocket closed (stale): \(closeCode) reason: \(reasonStr ?? "none")")
                return
            }
            print("[sync] WebSocket closed: \(closeCode) reason: \(reasonStr ?? "none")")
            self.isConnected = false
            self.scheduleReconnect()
        }
    }

    nonisolated public func urlSession(
        _ session: URLSession,
        task: URLSessionTask,
        didCompleteWithError error: Error?
    ) {
        if let error {
            Task { @MainActor in
                // Only reconnect if this is still the active WebSocket
                guard (task as? URLSessionWebSocketTask) === self.webSocket else {
                    print("[sync] WebSocket connection failed (stale): \(error.localizedDescription)")
                    return
                }
                print("[sync] WebSocket connection failed: \(error.localizedDescription)")
                self.isConnected = false
                self.scheduleReconnect()
            }
        }
    }
}
